### ISSUE TITLE
When was the data pulled?

### ISSUE THREAD

**Issue by bofstein** [paulgp/exit-poll-analysis#1]
Hi, I was looking for CSV files of CNN's exit poll data and found your helpful files.  A couple of numbers are different than what CNN currently displays though, as of 11/11/16 at 11am PST.  I wonder if some of the polls have been updated with any new info so I was wondering exactly what time you pulled the data to create the CSV files.

For example, Arizona Presidential Race by Gender shows that men voted 53-40 Trump-Clinton on CNN's website, but your uploaded file has 51-38.  Most cells are exactly the same but I'm trying to figure out these couple discrepancies.  Sorry if "Issues" isn't the right way to ask this question but I wasn't sure how else to.

**Comment by paulgp** [comment]
Hey, not a problem. I pulled these yesterday at 6pm PST. I suppose there
are two possible explanations: 1) rounding error on the database-side that
they adjusted or 2) they got more data. Is the sample size the same?

**Comment by bofstein** [comment]
Sample size is the same so I guess that's not it.  The vast majority that I checked (didn't check all of course because that would defeat the purpose of finding a CSV file instead of copying it all by hand) were exactly the same, occasionally they were 1% off so I figured that was rounding, but then some were 2% off like this one and one other that didn't seem like rounding would affect.

**Comment by bofstein** [comment]
Arizona in particular looks like many of the numbers are off by a large degree

**Comment by paulgp** [comment]
Ok, that's annoying. Thanks for catching it! I will resave the .htm files
and reparse. If you are comfortable running python, you can update the
files yourself -- just download the python code and dump the different htm
files into the folder.

**Comment by bofstein** [comment]
Unfortunately I don't know python or any other coding languages except a bit of R.  Thanks so much for doing this and putting it up!

**Comment by paulgp** [comment]
No problem, thanks for checking. I will update when I repull and parse.

**Comment by paulgp** [comment]
Hi, I updated the polls HTML data and pushed the new csv files. They should reflect the most up to date exit poll data. I'm closing this bug now.
